[tool.poetry]
name = "browserstack tests"
version = "1.0"
description = "Browserstack tests"
authors = ["Olga Zatulivetrova"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
